packages:
  - log-server
  - utils
  - gateway-server
  - hello-server
  - video-manage

onlyBuiltDependencies:
  - '@nestjs/core'
  - cpu-features
  - esbuild
  - ssh2
  - unrs-resolver

catalog:
  '@nestjs/common': ^11.0.1
  '@nestjs/core': ^11.0.1
  '@nestjs/mapped-types': ^2.1.0
  '@nestjs/platform-express': ^11.0.1
  '@nestjs/platform-socket.io': ^11.1.6
  '@nestjs/typeorm': ^11.0.0
  '@nestjs/websockets': ^11.1.6
  '@hono/node-server': ^1.19.5
  'axios': ^1.12.2
  'class-transformer': ^0.5.1
  'class-validator': ^0.14.2
  'cross-env': ^10.0.0
  'dotenv': ^17.2.2
  'humps': ^2.0.1
  'hono': ^4.9.9
  'ioredis': ^5.7.0
  'ip': ^2.0.1
  'js-yaml': ^4.1.0
  'ms': ^2.1.3
  'nacos': ^2.6.0
  'pg': ^8.16.3
  'reflect-metadata': ^0.2.2
  'rxjs': ^7.8.1
  'socket.io': ^4.8.1
  'socket.io-client': ^4.8.1
  'ssh2': ^1.17.0
  'typeorm': ^0.3.26
  'winston': ^3.18.1