version: '3.8'
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API 端口
      - "9001:9001"  # Console 端口
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
